### PR TITLE
Enable HW Key Vibration

### PR DESCRIPTION
**Pull request by thp1997**
Tested. HW Key Vibration is working Fine.

### CODE REVIEW

**Comment by TheScarastic** [comment]
i dont think we want to do this prolly you may find some better altenative ?

**Comment by thp1997** [comment]
I think so.

**Comment by TheScarastic** [comment]
virtual flag in above file enables vibration for hw keys which i have already done here https://github.com/TheScarastic/android_device_xiaomi_mido/commit/7a0ec5d5883af369aaaafcf8a630732bdfa2468b and overriding generic.kl doesnt seems good idea as well

**Comment by thp1997** [comment]
Its okay. Vibration was not working for single press so that's why i did set those flag to Vitual.

**Pull request closed without merging**
